include ../compilerSettings_clang-latest.mk

SOURCES=RangesV3Demo_View.cpp
EXECUTABLE=RangesV3Demo_View
CPPFLAGS = -Wno-unknown-warning-option -std=c++1z -I../externals/ranges/include

include ../makeCommon.mk
