#define MESSAGE_1 1
#define MESSAGE_2 2
#define MESSAGE_3 3
#define MESSAGE_4 4
#define DUPLICATE_MESSAGE_4 4

template <int N>
class MULTIPLE_DEFINITION_OF_THIS_CLASS_MEANS_DUPLICATE_MESSAGE_DEFS
{
};

template <>
class MULTIPLE_DEFINITION_OF_THIS_CLASS_MEANS_DUPLICATE_MESSAGE_DEFS<MESSAGE_1>
{
};

template <>
class MULTIPLE_DEFINITION_OF_THIS_CLASS_MEANS_DUPLICATE_MESSAGE_DEFS<MESSAGE_2>
{
};

template <>
class MULTIPLE_DEFINITION_OF_THIS_CLASS_MEANS_DUPLICATE_MESSAGE_DEFS<MESSAGE_3>
{
};

template <>
class MULTIPLE_DEFINITION_OF_THIS_CLASS_MEANS_DUPLICATE_MESSAGE_DEFS<MESSAGE_4>
{
};

template <>
class MULTIPLE_DEFINITION_OF_THIS_CLASS_MEANS_DUPLICATE_MESSAGE_DEFS<
    DUPLICATE_MESSAGE_4>
{
};


int main()
{
}
