include ../compilerSettings_g++concepts.mk

OPT=3
SOURCES=InlineVariantVisitorTimings.cpp
EXECUTABLE=InlineVariantVisitorTimings
CPPFLAGS += -I../externals/eggs_variant/include

include ../makeCommon.mk
