include ../compilerSettings_g++concepts.mk

CPPFLAGS += -I../externals/eggs_variant/include
SOURCES=ComposeableConceptRestrictedFunctionObject.cpp
EXECUTABLE=ComposeableConceptRestrictedFunctionObject

include ../makeCommon.mk
