include ../compilerSettings.mk

SOURCES=NestedInheritance.cpp
EXECUTABLE=NestedInheritance

include ../makeCommon.mk

NestedInheritance.o: NestedInheritance.cpp NestedInheritanceTraits.h \
  BaseTypeTraits.h
